title: Md. Shalahuddin
description: Software Engineer, Army War Game Centre.
baseurl: "/shantocv/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "shalahuddinshanto@gmail.com"
linkedin: "http://linkedin.com/in/shanto462"
github: "https://github.com/shanto462"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
